### ISSUE TITLE
Conda packaging

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#125]
Conda is a cross-platform general-purpose package manager that is especially popular among Python users. It can be especially useful for deploying packages that have compiled components, allowing these to be isolated in consistent environments with their dependencies. The Anaconda distribution of Python (which is based on Conda) is recommended to scientists in the Software Carpentry introductory courses.

Cross-platform dendency management is a significant challenge for the Mantid Project, and [the Technical Steering 
Committee has indicated that "conda first" approach will be preferred](https://github.com/mantidproject/documents/blob/master/Project-Management/TechnicalSteeringCommittee/meetings/2021/2021-02-02.md).

In order to simplify the packaging of Euphonic with Mantid and to aid compatibility with the spglib and matplotlib dependencies (which can be tricky to build with Pip) I propose that an official Conda package is provided for Euphonic.

**Comment by mducle** [comment]
If Euphonic is going with Conda, then I think that `pace-python` (and maybe Brille) should also provide a conda package...

Also to note that you don't need to provide a conda package for Euphonic to work with conda - `pip` packages can be installed in conda environments... but I guess the dependency issue is the main thing here.

**Comment by ajjackson** [comment]
Right, it's as much about getting Euphonic's dependencies installed safely. But would also be good to provide easy access to a known good build of the C extension.

**Comment by rebeccafair** [comment]
See https://github.com/conda-forge/staged-recipes/pull/14504

**Comment by ajjackson** [comment]
Update on this: it seems to be building ok and we're waiting for the conda-forge team to take a look.

**Comment by ajjackson** [comment]
Update: this has been accepted and I have been able to install via conda :tada: 

However, the "minimal" installation this provides is not very useful without the optional packages for Phonopy import and plotting. I wonder if we should consider a minimal `euphonic-base` package that is complemented by more full `euphonic` package.

Or maybe it would be sufficient at this point to give some useful conda install commands in the documentation? Then the user can copy-paste a command that includes the most useful optional dependencies.

**Comment by rebeccafair** [comment]
> Or maybe it would be sufficient at this point to give some useful conda install commands in the documentation? Then the user can copy-paste a command that includes the most useful optional dependencies.

This would be a good idea to do first, as currently we don't have any reference to Conda in the docs at all! Also, all the `import matplotlib` etc. error messages reference pip install only, maybe it would be sensible to add some conda help too? 

What are the use-cases for the Conda Euphonic package? At the moment its only the Mantid install for use from Abins right? How does that work? Would it be a problem in the future if Conda `euphonic` behaviour changed from installing the bare minimum to installing all the optional dependencies? (If we add a new `euphonic-base`)

**Comment by ajjackson** [comment]
> Would it be a problem in the future if Conda euphonic behaviour changed from installing the bare minimum to installing all the optional dependencies? (If we add a new euphonic-base)

Less of a problem than reducing the feature set, I think!

> What are the use-cases for the Conda Euphonic package? At the moment its only the Mantid install for use from Abins right?

That's the only one in the pipeline right now. The benefits would also apply for other packages looking to integrate Euphonic; using conda should help with getting the binary stuff to play together more reliably.

**Comment by rebeccafair** [comment]
Euphonic is available on the `conda-forge` channel (https://github.com/conda-forge/euphonic-feedstock), and v0.5.1 works on Windows thanks to #151. New issues should be opened if we decide to add more Conda packages (e.g. `euphonic-base`)
