### ISSUE TITLE
Optimise adaptive broadening

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#135]
As implemented in #131, use of `scipy.stats.norm.pdf` to calculate a Gaussian for each q-point and phonon mode in `calculate_dos` is very slow, we should investigate strategies to speed this up.

**Comment by ajjackson** [comment]
Update: an STFC Graduate rotation project has been assigned to this problem. In September we will be welcoming a mathematician to the team, who will look at the proposed strategies for this and do some implementation work as well as formal analysis.
