### ISSUE TITLE
Wrong Jenkins SHA1 for PR builds

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Euphonic#153]
Github requires [notifications](https://docs.github.com/en/rest/reference/repos#create-a-commit-status) to be triggered on the *commit* which triggers a build. For builds off branches this is fine, but for PR builds, github creates a merge commit which merges the PR branch into `master` and then sends *this* commit to Jenkins. 

The `Jenkinsfile` currently triggers notification on the commit it's sent but for PR builds, this is the wrong commit to show up in the PR (which is the commit of the branch rather than the merge commit).

**Comment by rebeccafair** [comment]
Closed by #154
