### ISSUE TITLE
Determine scheme for grouping/selecting spectra from metadata

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#161]
From discussion in #155 it's been determined that to properly handle PDOS we should have some method of grouping/selecting certain spectra by their metadata. This may influence #124.

**Comment by ajjackson** [comment]
As I see it our options are:
- implement a clever general scheme right now, which _may_ require some redundant "shortcut" methods for common use-cass
- implement an option for the most useful case (element selections) now, which can become a special-case/wrapper when a clever general scheme is added later

**Comment by ajjackson** [comment]
Here's some inspiration: how to do it with Pandas https://medium.com/analytics-vidhya/split-apply-combine-strategy-for-data-mining-4fd6e2a0cc99

**Comment by rebeccafair** [comment]
Fixed by #167 as  part of feature PR #138
