### ISSUE TITLE
-reorder flag will not correctly reorder phonon bands incorrect with -grace flag

### ISSUE THREAD

**Issue by durhamb-york** [pace-neutrons/Euphonic#19]
When I run dispersion.py to generate a phonon band structure using the following command:
`$ dispersion.py -reorder -grace Si_wall.phonon`
This will generate a different band structure from the band structure generated for matplot when dispersion.py is run without -grace flag:
`$ dispersion.py -reorder -grace Si_wall.phonon`
Resulting in following two dispersion plots.
![Reordered_correctly_matlab](https://user-images.githubusercontent.com/60005356/72638266-ffd1c980-395a-11ea-88c8-a1e84e81f438.png)
!['Reordered'_incorrectly_grace](https://user-images.githubusercontent.com/60005356/72639741-34935000-395e-11ea-823a-29750a0a62ac.jpg)
Looking at the range of 0.8-1.0 eV it can be seen there are some bands which are 
reordered in the matplot image and not reordered in the grace plot.

It is possible this is related to other warning message the code prints out:
```
UserWarning: PyGrace is not installed, attempting to write .agr Grace file anyway. If using Python 2, you can install PyGrace from https://github.com/pygrace/pygrace
  output_grace(data, seedname, up=args.up, down=args.down)
```

**Comment by rebeccafair** [comment]
Thanks for bringing this to my attention! Originally, the support from Grace output was added to enable the same functionality as CASTEP's dispersion.pl and dos.pl scripts, however as the project has progressed keeping this functionality may no longer be appropriate, as it adds additional maintenance overhead (especially as I don't use Grace myself) and we should be encouraging users to use Matplotlib. As a result, I was considering removing the Grace functionality completely in a future release.

Is the Grace output something that you need? Or would you be able to just use Matplotlib? If lots of users require Grace output maybe it's something we could reconsider.

**Comment by rebeccafair** [comment]
It has been decided to implement Grace plotting (and other CASTEP-specific functionality) in a separate project at https://bitbucket.org/castep/dispersiondos at some point in the future. So I'll close this issue.
