### ISSUE TITLE
Ability to save output of Spectrum1D / Spectrum1DCollection to text

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Euphonic#190]
Sometimes, it's necessary to use another package (e.g. Origin, Matlab) to plot data generated / calculated by Euphonic - e.g. to plot experimental and theoretical data together. At the moment, in order to do this, we have to extract the numpy array in `<obj>.[xy]_data.magnitude` and then use `numpy.savetxt` or something similar. This means that some metadata is lost when this is done. It would be good if Euphonic could provide a convenience function to do this - e.g. in addition to `to_json_file` we can have a `to_text_file` method (or `to_txt_file`?).

The generated text file should be (N+1)-columns where N is the number of Spectrum in the collection and there should also be `#` delimited comments indicating what the columns are (e.g. the contents of the `metadata` field) and also what units each column quantity is in.

E.g. something like:

```
# Spectra generated by Euphonic
# Column 1: x_data in (millielectron_volt)
# Column 2: y_data[0] species="O" weighting="coherent" in (barn / millielectron_volt)
# Column 3: y_data[1] species="Zr" weighting="coherent" in (barn / millielectron_volt)
0, 0, 0
0.1, 0, 0
0.2, 0, 0
...
```

**Comment by ajjackson** [comment]
This does look practical and not too difficult. One potential challenge for end-users would be parsing the metadata section which can have a variable number of entries and is not consistently ordered. But I suppose if this data is in a commented line then there is an implication that it would be processed manually? So really only the CSV part needs to be "machine-readable".

**Comment by mducle** [comment]
Yeah... we could include the number of columns / number of header lines in the first line.

The alternative is just to have a single comma-separated header line, but there is quite a bit of metadata and it would then be a bit harder for a human to read... e.g.

```
# x_data (millielectron_volt), "O-coherent" (barn / millielectron_volt), "Zr-coherent" (barn / millielectron_volt)
0, 0, 0
0.1, 0, 0
0.2, 0, 0
```

This would could then be automatically ingested into Origin with the labels automatically set - but it kind of assumes that you always have a `species` / `weighting` field... the per-line comments is a bit more flexible; or we could just specify rules for automatically constructing labels (if a `label` field does not exist - maybe if it exists just use it?)

**Comment by mducle** [comment]
Some feedback from users:

* Multi-line headers are prefered (for human-readability).
* It would be good to know the original file used to generate a spectra (e.g. a `.phonon` or a force constants file).

Unfortunately the second request would meen some changes to the `ForceConstants` and `QpointPhononModes` classes to record the original files... and also some link between `Spectrum` objects and the classes which creates them... this might be a bit too much...?

**Comment by ajjackson** [comment]
Number of lines shouldn't really be an issue, that's what the # are for.

I'm not keen to give filenames special treatment as an important piece of metadata, because it's easy to imagine cases in which there is no filename, there are multiple filenames, or multiple sets of data have identical filenames.

But it could go in the regular metadata field in contexts where that makes sense to do, without any modifications to underlying objects. And a text writing system should be robust against any metadata usage.  Considering a slightly more complex case, perhaps a collection with metadata

```python
{'weighting': 'coherent', 'filename': 'ZrO2-442.phonon':
 'line_data': [{'species': Zr}, {'species': O, 'site': 1}, {'species': O, 'site': 2}]}
```

would appear as

```
# Spectra generated by Euphonic
# Common metadata: weighting="coherent" filename="ZrO2-442.phonon"
# Column 1: x_data in (millielectron_volt)
# Column 2: y_data[0] species="Zr" in (barn / millielectron_volt)
# Column 3: y_data[1] species="O" index=1 in (barn / millielectron_volt)
# Column 4: y_data[2] species="O" index=2 in (barn / millielectron_volt)
0, 0, 0, 0
0.1, 0, 0, 0
0.2, 0, 0, 0
...
```

We should be a bit careful with quoting/escaping the metadata keys and values (maybe it should be `"weighting"="coherent"`) because the user is allowed to include spaces in metadata keys.

**Comment by ajjackson** [comment]
In this case I would not think that Euphonic's API should have any provision for tracking the filename with forceconstants/modes, but the CL tools (and user scripts, external codes) could insert this metadata as desired after spectra are generated and before exporting.
