### ISSUE TITLE
Kinematic constraints on powder maps [nice to have]

### ISSUE THREAD

**Issue by davidvoneshen** [pace-neutrons/Euphonic#200]
The powder maps tool is extremely useful but it would be nice to be able to apply the kinematics to the plots (i.e. mask out regions which cannot be accessed). This should (in my opinion) be done in a simple and generic way where we just ask for a lowest and highest 2theta and the fixed Ei or Ef. More complex geometries should remain the preserve of users.

The Q of a detector for a given Ki and Kf is 

Q=np.sqrt(ki**2+kf**2-2*np.abs(ki*kf)*np.cos(ang*np.pi/180))
while the Energy is 
E=2.07*(ki**2-kf**2)
assuming that Ei and Ef are in meV and Ki and Kf are in angstrom. 

If we were to simply set all points which lie outside this range to NaN (which matplotlib appears to deal nicely with) it would give a nicer comparison to the experimental Q-E maps.

**Comment by ajjackson** [comment]
@davidvoneshen I have cobbled together some code off the back of the Abins implementation. Can you have a look at #204 and see if the maths is correct?

(The easiest way to do that would be to put in some real-world numbers!)

There is room for refinement: at the moment it checks if the mid-bin value is in the accessible range, but I think it will be useful to make the masking slightly more generous and include any bins that overlap with the edge. This would then allow e.g. single detectors to be mapped out by setting equal upper and lower angle limits. Particularly nice for instruments like TOSCA? (Especially if it can then be flattened to 1D :thinking: )
