### ISSUE TITLE
Error estimation for Brille interpolation

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#206]
Building on #95  and playing with the implementation in #104 it would be useful to get some information about the error associated with linear interpolation.

I propose to achieve this by
- implementing 3-d quasirandom sampling of the Brillouin zone to obtain a set of low-symmetry reference points
- creating a command-line tool that compares linearly-interpolated points from Brille with "exact" Fourier-interpolated points from Euphonic

If appropriate this might lead to sampling recommendations or an automatic convergence scheme.

**Comment by rebeccafair** [comment]
Merged into Brille feature branch in #207, included in `euphonic-brille-convergence` command-line tool, and merged into master in #104.
