### ISSUE TITLE
Problem reading Phonopy with 'au' units

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#210]
[Some Phonopy calculators](https://phonopy.github.io/phonopy/interfaces.html) use 'au' as a unit meaning Bohr, unfortunately Pint interprets this to mean Astronomical Unit, leading to some interesting results...

Thanks @ajjackson for finding this.

**Comment by alinelena** [comment]
replacing au with bohr in the .yaml seems to do the trick. in theory I suspect phonopy shall write it correctly. maybe euphonics can intercept au and change it to bohr.. but I still think phonopy shall write the proper unit.
