### ISSUE TITLE
Arbitrary scale factors

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#219]
For ease of comparison with other codes and normalisation conventions, it would be useful if most CLI outputs had an option to apply an arbitrary scaling factor.

An interesting variation would be to also allow unit conversions. How might those options work together?

**Comment by rebeccafair** [comment]
Speaking of normalisation, one thing I've noticed is that we normalise structure factors per atom, whereas we normalise DOS to modes per unit cell (integrated area is 3*n where n is the number of atoms in the unit cell).

Is this inconsistent? Should both be per atom? It should at least be documented in `calculate_dos` as I don't think it says in the docstring currently.

**Comment by ajjackson** [comment]
I'd be happy with per-atom for consistency (i.e. sums to 3).

I think the more popular conventions are unit cell (as implemented, sums to 3N) and dividing by 3N (sums to 1). We've already discussed issues with unit cell normalisation! The factor of 3 is easy to account for if necessary as long as it is clearly documented.

As this would be a change in results, maybe that convention change should also target the v1 release branch?

**Comment by rebeccafair** [comment]
Use `__mul__`
