### ISSUE TITLE
Consider bumping Numpy/Pint for cleaner function calls

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#247]
Euphonic currently has minimum versions of Pint=0.10 and Numpy=1.14.5. These are quite conservative given that the minimum Python version is not 3.7.
- The highest available versions on Python 3.6 are Pint 0.17, Numpy 1.20
- The highest available versions on Python 3.7 are Pint 0.18, Numpy 1.21

I am generally in favour of supporting old library versions if there is little harm. Research computing environments are often somewhat slow-moving and dependency management can be a pain even with Pip and Conda when we want to run multiple programs in the same environment.

A particular pain-point with this Numpy/Pint version combination is that some useful Numpy functions do not work as expected when applied to Quantity inputs. This requires workarounds for compatibility over a wide range of versions (i.e. casting to magnitude and re-applying units after the Numpy operation). A couple of examples are

```python
np.diff(np.array([1, 2, 3, 4, 6, 8]) * ureg('meV'))
```
With Pint 1.10, this works correctly with Numpy 1.17+ but with Numpy 1.16 the units are stripped and a bare ndarray is returned.

```python
np.isclose(4., np.array([2., 3., 4., 4.]))
```
- with Pint 1.10 and Numpy 1.16, this incorrectly finds all elements to be False
- with Pint 1.10 and Numpy 1.17, the answer is correct but a warning is raised
- with Pint 1.11+ and Numpy 1.17, the answer is correct.

I suggest we can avoid some development headaches and improve code readability by slightly upping the requirements to Pint 1.11 and Numpy 1.17, and using `git grep` to identify' and clean up application of these functions. 
Doubtless there are other examples, but I don't propose going out of our wy to find them now.

**Comment by ajjackson** [comment]
`np.copy(data: Quantity)` would be another beneficiary; this gets used quite a bit in Spectrum methods

**Comment by oerc0122** [comment]
This appears to be out of date as minimum versions are:
numpy==1.24.0
pint==0.22

**Comment by ajjackson** [comment]
Yes, these got adequately bumped when moving the minimum Python version to 3.10 (i.e. since last release).
