### ISSUE TITLE
A partial DOS

### ISSUE THREAD

**Issue by HoloHolo-phys** [pace-neutrons/Euphonic#268]
Hello there! Thank you very much, I really appreciate your hard work and dedication to euphonic project! I was wondering if I could suggest a small improvement that could make the project even better.

Would it be possible to add a feature to calculate a partial DOS? Specifically, it would be great if the partial DOS could be calculated in a form of three components x, y, z corresponding to eigenvector orientation, similar to how it is currently implemented in PHONOPY. It however is lacking this cool adaptive width regime... Additionally, it would be useful to have the option to separate the DOS into different atoms.

Thank you for considering my suggestion, and keep up the great work!

**Comment by mducle** [comment]
Thanks for your suggestion. I guess you mean the `XYZ_PROJECTION` in phonopy ([documented here](https://euphonic.readthedocs.io/en/latest/dos.html#adaptive-broadening))?

Partial DOS split by atomic components is [already available](https://euphonic.readthedocs.io/en/latest/howto.html#producing-a-dispersion-or-density-of-states) (including with adaptive broadening) - if you use the broadening syntax described [here](https://euphonic.readthedocs.io/en/latest/dos.html#adaptive-broadening), just replace `calculate_dos` with `calculate_pdos`. 

Unfortunately, the original author and main developer of Euphonic recently left the team, so we're a bit short-handed at the moment, so I don't think we can implement this feature in the near future.

**Comment by HoloHolo-phys** [comment]
Oh, I see. For some strange reason, I was reading the pretty old version of documentation (0.4v) and could not find that it is already implemented. The PDOS in your link is exactly what I wanted.

Thank you for your quick response! I guess this issue can be closed.

**Comment by ajjackson** [comment]
What application do you have in mind for the (x, y, z) projections? In principle we can add this feature request to the backlog, but I have learned from working on Sumo that things get hard to maintain if we add a new command-line argument for every use case!

In particular, the design space of useful combinations of DOS projections is almost infinite and difficult to capture with command-line syntax. (e.g. one wishes to plot the total contribution of one H atom against all the (1, 1, 1) in-plane contributions of the other atoms and the out-of-plane contributions split by element...) This may be better suited to a custom Python script?

**Comment by HoloHolo-phys** [comment]
In high symmetry systems, the spectra can have modes with distinct orientation. For instance, you have several low energy optic modes with z-orientaton and one degenerate xy-optic mode in vicinity. And if you plot a total DOS it will be a combination of all of that.

The dispersion of z-optics may have some features like zero gradient at boundary point, leading to singularities in DOS. Meanwhile, the xy-mode go in much higher energies giving just boring quadratic background at the energies, where something interesting occurs with z-component. One can want to show them separately, so a z-part not obscure features of xy-part and vice versa.

I not insist on this feature anyhow, and, actually, since I only now found the current version of documentation lol, maybe I can work through it myself with a custom script as you suggested. Anyway, it is hard for me to estimate how useful this will be to someone else.
