### ISSUE TITLE
Recommend pre-installing Numpy

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#272]
If Numpy is not installed already, there can be errors during installation as the compiler looks for numerical libraries.

We could recommend installing Numpy before other packages to make that more deterministic. The trouble is that then we aren't really using the package versioning from setup.py and our recommended version will inevitably get out of date...

(This behaviour was encountered in docs builds during #271 )

**Comment by oerc0122** [comment]
Is this solved by #324 ?

**Comment by ajjackson** [comment]
Solved in a greatly superior fashion, yes
