### ISSUE TITLE
Increase Python requirement to 3.8

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#278]
- Official end-of-life for Python 3.7 is June 27 2023
- Mantid is now built on at least Python 3.8 so this will not cause problems there
- We have started spotting places  in the code that it would be nice to use the [assignment expressions](https://peps.python.org/pep-0572/) (aka "the walrus operator")
- Some other Python 3.8+ features to consider using
  - positional-only parameters (probably not relevant, but could be used for more robust passing of **kwargs to matplotlib etc)
  - `@lru_cache` no longer requires an argument to decorate a function
  - `@functools.cached_property` looks handy
  - `@functools.singledispatchmethod` provides a cleaner handling of type-dispatched methods; this could be used to clean up e.g. the Spectrum objects that have a lot of type-dispatching.
  - `math.dist()` calculates Euclidean distance. Mostly we would use `np.linalg.norm` for this but it might be the better option if the data isn't already in numpy arrays.
  - `math.prod` - finally something like a lisp (* ...) for multiplication of an arbitrary number of arguments :grin: .
  - `multiprocessing.shared_memory` module (not that we should stop using C/OpenMP for "hot" parts of the code!)
    - This could be very useful for enumerating 2-phonon incoherent scattering combinations; currently Abins does this in serial
  - `typing.TypedDict` provides a proper way to type-hint heterogeneous dictionaries. Of course, a lot of those could be NamedTuple or dataclass, but for existing or JSON-imported dictionaries this is good.
  - `typing.Literal` to define a specific set of allowed values. We could be using this for e.g. 'gauss', 'lorentz' broadening options.

**Comment by sf1919** [comment]
Mantid is moving to Python 3.10 at the moment ready for v6.8 release in October.
