### ISSUE TITLE
plot_1d generates two identical plots in Jupyter notebooks

### ISSUE THREAD

**Issue by mducle** [pace-neutrons/Euphonic#301]
Code to reproduce to follow.

**Comment by ajjackson** [comment]
I think this will be to do with the functions _returning_ a Figure object as well as the Jupyter/matplotlib setup identifying that a plot was created.

If the last line of your code block was
`plot_1d(...)`
try replacing it with
`_ = plot_1d(...)`

so the new Figure is swallowed by a variable and Jupyter doesn't try to "helpfully" show it (again).

**Comment by mducle** [comment]
@ajjackson Thanks I think that this is the reason. In the solution which [Becky wrote](https://github.com/mducle/edatw24/blob/main/solutions/day5_euphonic_solution.ipynb) the plots only appear once but she always assigned the output of `plot*` to a variable.

I guess this means that we should close this as `wontfix` or `no-a-bug` (although we don't have such a label...)
