### ISSUE TITLE
discontinuities when using Lorentzian broadening

### ISSUE THREAD

**Issue by davidvoneshen** [pace-neutrons/Euphonic#302]
when using .broaden(method='lorentz') you get discontinuities in the tails of intense modes (see attached). This is probably related to the settings for correlate 1d where we are padding the edges with zeros. We should probably figure out a superior option and make it available somehow. It isn't an obvious problem for Gauss or when all your modes have similar intensities

![euphonic-discontinuities](https://github.com/pace-neutrons/Euphonic/assets/48722944/86c02ac0-ebe9-4398-8dc4-74b1ff38e964)

**Comment by ajjackson** [comment]
Hi @davidvoneshen , I'm struggling to reproduce this. If I create a visually similar broadening on a single peak I see no such truncation. Do you have a minimal script to demonstrate the issue that I can play with? Feel free to email if you'd rather not have it public on Github!

**Comment by ajjackson** [comment]
```python
﻿from euphonic import ureg, Spectrum1D
from euphonic.plot import plot_1d, plot_1d_to_axis
import numpy
from toolz import first, second

raw_data = [(5, 100),
            (12, 180),
            (20, 20),
            (25, 5),
            (33, 5)]
bins = numpy.linspace(0, 40, 400)

intensities, _ = numpy.histogram(numpy.fromiter(map(first, raw_data), float),
                                 bins=bins,
                                 weights=numpy.fromiter(map(second, raw_data), float),
                                 density=False)

spectrum = Spectrum1D(bins * ureg("meV"),
                      intensities * ureg("1 / meV"))

broad_spectrum = spectrum.broaden(shape="lorentz", x_width=(5 * ureg("meV")))

fig = plot_1d(spectrum, color="k")
plot_1d_to_axis(broad_spectrum, ax=fig.gca())
fig.savefig("lorentz.png", dpi=300)
```

gives me

![lorentz](https://github.com/user-attachments/assets/6cf1099d-3490-4366-8724-9ef86b9cff3f)

**Comment by ajjackson** [comment]
A-ha, I was able to reproduce it with euphonic 1.2.1. This was fixed last year, you just need to update 😄 

![lorentz](https://github.com/user-attachments/assets/961816c4-d26f-475e-8647-8628dc8c9a3f)
