### ISSUE TITLE
Experiment with constraints file or `uv`

### ISSUE THREAD

**Issue by oerc0122** [pace-neutrons/Euphonic#345]
In order to run the tests with the minimum requirements it may be possible to use a [constraints file](https://pip.pypa.io/en/stable/user_guide/#constraints-files) rather than a requirements file. 

The constraints file is a standard way of specifying the version constraints on a particular build which may allow the min-requirements tests to require no specialised commands beside specifying the constraints file in the `extras`.

The alternative would be an overall migration to the [`uv` build system](https://docs.astral.sh/uv/) or [`pip-tools`](https://pypi.org/project/pip-tools/2.0.1/) which provide the ability to build minimum requirements sets.

**Comment by ajjackson** [comment]
Even under `uv`, a constraints file may be handy to deal with the "slightly different min requirements on Mac" problem.
