### ISSUE TITLE
Update Phonopy file IO to generate hdf5 summary file.

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Euphonic#43]
Phonopy currently outputs yaml summaries only where loading large force constants ~10x times faster using hdf5. 
See https://github.com/phonopy/phonopy/pull/108 for tips on updating flags and extending Phonopy file io.
Feature branch for read in https://github.com/pace-neutrons/Euphonic/tree/8_phonopy_interface_cp.

 #8

**Comment by rebeccafair** [comment]
The main I/O bottleneck for Euphonic/Phonopy, is loading large `band/mesh/qpoints.yaml` files using `yaml.safe_load`, but Phonopy can create already hdf5 versions of these files to avoid this. In comparison, reading force constants (even via .yaml) is fast and probably not worth the development effort to output them as hdf5.
