### ISSUE TITLE
Enable read of phonons/force constants when the Phonopy primitive cell was used

### ISSUE THREAD

**Issue by pjcon** [pace-neutrons/Euphonic#44]
Phonopy is not so transparent in its use of unit/primitive cells for force constants calculation. Euphonic Phonopy interface should detect when the primitive cell was used to generate the force constants file. See https://github.com/pace-neutrons/Euphonic/tree/8_phonopy_interface_cp

 #8

**Comment by rebeccafair** [comment]
The Phonopy reader (770eab9a7887437779f5085db34305e28652df88) can now handle reading frequencies/eigenvectors when the primitive cell was used. However, reading the force constants generated for the primitive cell is more difficult (see the [developer docs](https://github.com/pace-neutrons/pace-developers/blob/master/euphonic/other/01_phonopy_reader.md#interpolation-using-a-primitive-axis)). For now, this will not be supported.

**Comment by rebeccafair** [comment]
This isn't necessarily a problem with the primitive axis, it is more a problem with non-diagonal supercells in general. So I'll close this issue and open [another one](https://github.com/pace-neutrons/Euphonic/issues/54)
