### ISSUE TITLE
Cannot determine cell origins in Phonopy reader for some materials

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#77]
When reading the following file (uploaded with .txt instead of .yaml extension because of Github restrictions) [mp-147-20180417.txt](https://github.com/pace-neutrons/Euphonic/files/4813260/mp-147-20180417.txt), the following Exception is raised:

`Exception: Multiple possible cell origins found for force constants matrix`

**Comment by ajjackson** [comment]
Here are another three data files which give this result. All the files were generated using Phonopy from the corresponding entries in Atsushi Togo's phonon database at Kyoto University http://phonondb.mtl.kyoto-u.ac.jp/

[mp-7041-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4813584/mp-7041-20180417.yaml.txt)
[mp-216-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4813582/mp-216-20180417.yaml.txt)
[mp-917-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4813583/mp-917-20180417.yaml.txt)

**Comment by ajjackson** [comment]
And a few so-far-working examples: 
[mp-226-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4814180/mp-226-20180417.yaml.txt)
[mp-306-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4814181/mp-306-20180417.yaml.txt)
[mp-661-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4814182/mp-661-20180417.yaml.txt)
[mp-1818-20180417.yaml.txt](https://github.com/pace-neutrons/Euphonic/files/4814183/mp-1818-20180417.yaml.txt)

Again, these are derived from Togo's database which is under a CC-by license. This is a very permissive license, as long as we give attribution, link to it https://creativecommons.org/licenses/by/4.0/ and explain if we have changed it.

**Comment by rebeccafair** [comment]
Testing on a variety of materials has revealed #81. This is blocked until that is resolved.

**Comment by rebeccafair** [comment]
For future reference a description of this problem solution is detailed here: https://github.com/pace-neutrons/pace-developers/blob/master/euphonic/other/01_phonopy_reader.md
