### ISSUE TITLE
Store scattering lengths in Euphonic

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#78]
Currently, users must look up their own scattering lengths and input a dictionary to `calculate_structure_factor`. This should still be possible, but there should also be sets of scattering lengths stored in Euphonic so that users aren't required to look them up.

**Comment by mducle** [comment]
SpinW has a copy of the lengths from NIST here: https://github.com/SpinW/spinw/blob/master/dat_files/isotope.dat
