### ISSUE TITLE
Add CI for building the docs

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#82]
We should check that the docs build without error on new pull requests, to avoid unpleasant surprises.

If we're moving to a self-hosted docs platform, then this should probably happen at the same time?

**Comment by rebeccafair** [comment]
I agree! Maybe we should start using a 'blocked' label? I can't actually find an issue in the PACE project board for moving the documentation, one should probably be added

**Comment by rebeccafair** [comment]
Blocked by #83

**Comment by rebeccafair** [comment]
This has been enabled from the Readthedocs Euphonic project by enabling `Settings` > `Advanced Settings` > `Build pull requests for this project`. Permissions for Readthedocs app to access the pace-neutrons organisation also had to be [requested](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps). 

See [here](https://docs.readthedocs.io/en/stable/pull-requests.html) for more information.
