### ISSUE TITLE
Spectrum objects: inheritance, consider exposing more to public API

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#86]
While working on the plotting, the `_get_bin_edges()` and `_get_bin_centres()` methods are proving very useful. It's not ideal to be using private attributes from another module, though. Is there a reason these are not part of the public API?

As far as I can tell it would be a _bad_ idea to use the `x_data` and `y_data` attributes, because if you have received a Spectrum as an argument or from a file you don't know if those are bin centre or bin edge values. (Unless you reproduce the effort to compare some array sizes!)

Also, I see that Spectrum2D inherits from Spectrum1D. That seems dangerous because it means that `isinstance(my_2d_data, Spectrum1D) == True`. Was there a deliberate decision against having these both inherit from an abstract base class?

**Comment by rebeccafair** [comment]
There's no particular reason that `_get_bin_edges/centres()` are private, apart from I didn't have a specific use-case to make them public, though calling them from another module even if its within Euphonic is bad practice so they probably _should_ be made public. And yes, the idea was to avoid having to keep using a the same few lines of code over and over to determine whether `x_data` and `y_data` are edges or centres.

I didn't think about the `isinstance` issue, I don't see a reason why they couldn't both inherit from `SpectrumND` or something similar.
