### ISSUE TITLE
Rework of 1D and 2D spectrum plotting

### ISSUE THREAD

**Issue by ajjackson** [pace-neutrons/Euphonic#87]
Work on the Spectum2D plotting in #85 has naturally led to consideration of Spectrum1D and a consistent interface for features that have emerged.

An outline of a possible setup, mostly based on a Slack discussion with @rebeccafair.

- Define a Spectrum1DCollection, which contains a sequence of Spectrum1D with a common x-axis
  - The main purpose of this is to resolve any ambiguity in "band structure"-like data by guaranteeing common x-axis coordinates/labels, and clearly distinguishing between a sequence of lines and a sequence of plots
  - In addition it would handle iteration of operations applied to the whole collection, such as atom-projected DOS broadening
  - No equivalent is needed for Spectrum2D, as these are not generally handled as a stack of data series to be overlaid.

- Separate the tasks of splitting spectra into regions and plotting them
  - The main purpose of this is to expose more useful atomic functions to users who may wish to use their own code for one part or another. The separation should also aid testing.
  - Splitting would be provided as methods with consistent interfaces on Spectrum1D, Spectrum1DCollection, and Spectrum2D
  - The function signatures of plotting functions become:
    ```python
    plot_1d(spectrum: Union[Spectrum1D, Sequence[Spectrum1D], Spectrum1DCollection, Sequence[Spectrum1DCollection]], **kwargs) -> Figure
    plot_2d(spectrum: Union[Spectrum2D, Sequence[Spectrum2D]], **kwargs) -> Figure
    ```
    where sequences will be plotted as multiple subplots, with widths scaled according to their x-data. This would primarily be used for dislocations in band structures, but might also be employed for skipping empty regions of DOS-like spectra.
  - These high-level plotting functions manage type dispatch, figure/axis construction and call to
    ```python
    plot_1d_basic(Spectrum1D, ax, **kwargs) -> None
    plot_2d_basic(Spectrum2D, ax, **kwargs) -> None
    ```

An overall consequence of this would be that
```python
plot_dispersion(QpointPhononModes) -> Figure
```

becomes
```python
plot_1d(QpointPhononModes.get_dispersion().split()) -> Figure
```
.

It is of course be possible to leave a `plot_dispersion()` convenience method/function in place if desired, but this pipeline provides many more opportunities for users and developers to extract and/or manipulate the data.

**Comment by ajjackson** [comment]
Maybe the basic plotters can be called e.g. `plot_1d_axis` 🤔

**Comment by rebeccafair** [comment]
> Maybe the basic plotters can be called e.g. `plot_1d_axis` 🤔

I quite liked `_plot_2d_core`, to me that makes it clear that it handles the lower-level stuff

**Comment by ajjackson** [comment]
I don't think they should be treated as private internals though. Specifying plot axes is good, people should do it more 😄

**Comment by rebeccafair** [comment]
`plot_1d_on_axis`?

**Comment by ajjackson** [comment]
`plot_1d_to_axis`?

**Comment by rebeccafair** [comment]
Good point, it probably should be `axes`. `plot_1d_on_axes` sounds more natural to me but `plot_1d_to_axes` works too!
