### ISSUE TITLE
Refactor util.py

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#90]
`util.py` is quickly becoming a dumping ground for any new functions that don't have an obvious place anywhere else. This has 2 main issues (and probably more):
- Makes it difficult to find the function that you want (increasing the chance of you rewriting it yourself and duplicating code functionality)
- Increases the amount of dependencies, given that many classes are imported in `euphonic.__init__` (which depend on `util`, which has lots of dependencies...) this increases the chance of circular dependencies

Effort should be made to refactor `util.py` out into separate files and/or put the functions into appropriate classes before it gets out of hand.

**Comment by ajjackson** [comment]
I'll add here that the specific practice which got me into dependency hell was importing classes to use in type annotations, e.g.

```python
from typing import List, Tuple
from euphonic.crystal import Crystal
def get_qpoint_labels(crystal: Crystal, qpts: np.ndarray) -> List[Tuple[int, str]]:
    ...
```

I think it would be a reasonable practice to avoid that specific problem by deferring the mypy imports with e.g.
```python
from typing import List, Tuple
import euphonic

def get_qpoint_labels(crystal: 'euphonic.Crystal', qpts: np.ndarray) -> List[Tuple[int, str]]:
    ...
```
It's not pretty but could at least be a consistent pattern within this file.

However we could easily hit this problem outside of type-hinting. It is not safe to import Euphonic classes at the top of this module, when so many of them use it. Deferred imports inside functions will sometimes help, but they make the problem harder to examine.
