### ISSUE TITLE
Rename scripts to be Euphonic specific

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#91]
Euphonic's utility scripts (e.g. `dispersion.py`, `dos.py`) have very generic names which could easily lead to clashes on a user's path. They should be renamed (e.g. `euphonic-dispersion`) and the old names deprecated so the old names can be removed in a future version.

**Comment by ajjackson** [comment]
Re: hyphens and underscores, as raised in https://github.com/pace-neutrons/Euphonic/pull/73#discussion_r478908139

In Sumo we solved this problem by putting scripts in a submodule `sumo.cli` with snake_case and/or abbreviated names.
We then use the `console_scripts` entry point to put them on PATH with hyphenated names, prefixed with `sumo-`. This way it is still practical to import stuff from those scripts for testing and/or hacking purposes.

**Comment by rebeccafair** [comment]
Good info, I'd be happy to do it that way, it seems sensible! Is it practical to do this for the new scripts in the current open PRs before I get around to updating the old scripts?

**Comment by ajjackson** [comment]
Should be quick to sort out in a new PR, I don't mind fixing in rebase for my PRs once that's resolved.

Here's the sumo setup file: https://github.com/SMTG-UCL/sumo/blob/master/setup.py

It's possible some other project members would have opinions about the existence of a CLI module in the main library (especially as they can be hard to test!) Any objections @abuts @nickbattam-tessella @g5t ? This approach is also used in ASE and Pymatgen.
