### ISSUE TITLE
plot_1d, plot_2d fail with numpy<1.17.0

### ISSUE THREAD

**Issue by rebeccafair** [pace-neutrons/Euphonic#98]
For `numpy<1.17.0`, `np.diff(Quantity)` strips the units and returns a plain Numpy array, this has been overlooked in `Spectrum1D._get_bin_edges` and `Spectrum1D._get_bin_centres`, so functions that use these (e.g. `plot_1d`, `plot_2d`) will not work. 

This raises a broader issue whether we should also be testing against the 'minumum' specified dependencies so things like this aren't missed in the future.

**Comment by ajjackson** [comment]
ASE does this by including an "oldlibs" environment in the CI tests. It's useful - and usually numpy is the culprit...

**Comment by rebeccafair** [comment]
Good to know! I'll have a look and raise an issue to implement some kind of old dependency testing..
